Repository NOW-SOPT-APP9-SPOTIFY/Spotify_Server, pull requests merged in 2024-05, with the labels that each got.

#3 [chore] postgresql 의존성 추가
  build.gradle
Labels: dependency

#5 [feat] 엔티티 생성
  src/main/java/com/spotify/spotifyserver/entity/Album.java
  src/main/java/com/spotify/spotifyserver/entity/Artist.java
  src/main/java/com/spotify/spotifyserver/entity/Playlist.java
  src/main/java/com/spotify/spotifyserver/entity/Song.java
Labels: db

#7 [feat] 공통 api response 생성
  src/main/java/com/spotify/spotifyserver/common/SpotifyResponse.java
  src/main/java/com/spotify/spotifyserver/common/SuccessCode.java
Labels: enhancement

#11 [fix] SpotifyResponse @Getter추가
  src/main/java/com/spotify/spotifyserver/common/SpotifyResponse.java
Labels: bug

#13 [feat] 오늘의 히트곡 api
  src/main/java/com/spotify/spotifyserver/controller/SongController.java
  src/main/java/com/spotify/spotifyserver/dto/SongGetResponse.java
  src/main/java/com/spotify/spotifyserver/dto/SongsGetResponse.java
  src/main/java/com/spotify/spotifyserver/repository/SongRepository.java
  src/main/java/com/spotify/spotifyserver/service/SongService.java
Labels: api

#12 [feat] 인기 아티스트 api
  src/main/java/com/spotify/spotifyserver/common/SpotifyResponse.java
  src/main/java/com/spotify/spotifyserver/controller/ArtistController.java
  src/main/java/com/spotify/spotifyserver/entity/Artist.java
  src/main/java/com/spotify/spotifyserver/repository/ArtistRepository.java
  src/main/java/com/spotify/spotifyserver/service/ArtistService.java
Labels: api

#16 [feat] 아티스트 상세 페이지 api 생성
  src/main/java/com/spotify/spotifyserver/common/SpotifyResponse.java
  src/main/java/com/spotify/spotifyserver/controller/ArtistController.java
  src/main/java/com/spotify/spotifyserver/dto/ArtistGetResponse.java
  src/main/java/com/spotify/spotifyserver/dto/SongResponse.java
  src/main/java/com/spotify/spotifyserver/entity/Artist.java
  src/main/java/com/spotify/spotifyserver/repository/ArtistRepository.java
  src/main/java/com/spotify/spotifyserver/service/ArtistService.java
Labels: api

#18 [fix] 인기 아티스트 api 변경
  src/main/java/com/spotify/spotifyserver/common/SpotifyResponse.java
  src/main/java/com/spotify/spotifyserver/controller/ArtistController.java
  src/main/java/com/spotify/spotifyserver/dto/ArtistDTO.java
  src/main/java/com/spotify/spotifyserver/service/ArtistService.java
Labels: api

#21 [feat] 아티스트 인기차트 상세 api 생성
  src/main/java/com/spotify/spotifyserver/controller/SongController.java
  src/main/java/com/spotify/spotifyserver/dto/PopularSongsResponse.java
  src/main/java/com/spotify/spotifyserver/repository/SongRepository.java
  src/main/java/com/spotify/spotifyserver/service/SongService.java
Labels: api

#24 [fix] api 오류 해결
  src/main/java/com/spotify/spotifyserver/common/SpotifyResponse.java
  src/main/java/com/spotify/spotifyserver/controller/ArtistController.java
  src/main/java/com/spotify/spotifyserver/controller/SongController.java
  src/main/java/com/spotify/spotifyserver/dto/ArtistDTO.java
  src/main/java/com/spotify/spotifyserver/service/ArtistService.java
Labels: bug
